FROM mcr.microsoft.com/dotnet/aspnet:3.1-focal
RUN apt update && apt install unzip && mkdir /usr/share/nop
WORKDIR /usr/share/nop
ADD https://github.com/nopSolutions/nopCommerce/releases/download/release-4.50.0/nopCommerce_4.50.0_NoSource_linux_x64.zip /usr/share/nop/nopCommerce_4.50.0_NoSource_linux_x64.zip
RUN unzip nopCommerce_4.50.0_NoSource_linux_x64.zip
EXPOSE 80
CMD ["/usr/bin/dotnet", "/usr/share/nop/Nop.Web.dll"]
